### ISSUE TITLE
Moving cursor over terminal window on macOS causes gping to quit

### ISSUE THREAD

**Issue by kkocel** [orf/gping#147] opened 2021-09-02 09:08 UTC
Steps to reproduce:

1. start `gping` in the terminal window 
2. move a cursor over the window 
3. `gping` quits with random characters in the terminal window eg.:
```console
$ 35;4;20M35;6;20<[3<<<<<;[23452<0;M[23452<0;M[23452<0;M[23452<0;M[23452<0;M[23452<0;M[23452<0;M^C
```

Expected behavior: `gping` should not quit

**Comment by orf** [comment] 2021-09-12 14:21
Hmm, I can't reproduce this at all. Can you share some more information about your environment?

**Comment by kkocel** [comment] 2021-09-12 18:29
@orf tbh after updating to macOS 11.5.2 (20G95) I can't reproduce it either.

**Comment by orf** [comment] 2022-01-15 15:48
Ok, thanks for letting me know. I'll close this for now.

**Closed by orf** 2022-01-15 15:48 UTC
